### ISSUE TITLE
Json parse error after a while

### ISSUE THREAD

**Issue by TheUberCatman** [voider1/teleborg#11]
For some reason the bot stops working, after some debugging i found out that the error is caused with parsing the updates.  The exact error message is `Err(JsonError(ErrorImpl { code: Message("invalid type: sequence, expected a string"), line: 0, column: 0 }))` i found this error printing `rjson` at `bot\mod.rs line 86`

**Comment by TheUberCatman** [comment]
after some debugging i may have found the issue, if you send an image, the bot fails parsing.

**Comment by TheUberCatman** [comment]
After some reproducing i can confirm the issue occurs when sending an image, possibly also when sending a video, document or audio.

**Comment by voider1** [comment]
Yes, it's probaby because serde tries to deserialize this as something else than a `String`.

**Comment by TheUberCatman** [comment]
I am going to solve this issue by adding the missing objects.

**Comment by voider1** [comment]
Alright, thank you!
