### ISSUE TITLE
Feature request: command arguments

### ISSUE THREAD

**Issue by TheUberCatman** [voider1/teleborg#2]
It would be nice to be able to get the passed arguments

**Comment by voider1** [comment]
I have implemented command arguments, cheers!

**Comment by mpwsh** [comment]
Hi voider, sorry to ask here, but i didn't find it in the docs.
How can i read the arguments after a command using your lib?

**Comment by Bertus-W** [comment]
To add a command handler you can see the readme. To read the arguments like in ‘/hello world’ you can read the ‘update’ parameter in your handler method. In the ‘update’ struct you will find ‘message’ and within ‘text’ that will give you ‘/hello world’ in this case

**Comment by mpwsh** [comment]
Thanks Catman!

This is what i came up with:

```
fn echo(bot: &Bot, update: Update, args: Option<Vec<&str>>) {
    let (bot, chat_id, _) = setup();
    let respond_arg: String = update.message.clone().unwrap().text.unwrap().replace("/echo", "");
    let message = bot.send_message(
            &chat_id,
            &respond_arg.to_string(),
            None,
            None,
            None,
            None,
            None,
        );
        assert!(message.is_ok());
}

```
Is there an easier way to do it?
